<?php
// Liste BIP39 officielle en français (2048 mots)
// Source : https://github.com/trezor/python-mnemonic/blob/master/src/mnemonic/wordlist/french.txt
function getBip39Fr(): array {
    return [
        'abaisser','abandon','abdiquer','abécédaire','abeille','abolir','aborder','aboutir',
        'aboyer','abraser','abriter','abroger','abrupt','absence','absolu','absurde',
        'abusif','abyssal','académie','acajou','acarien','accabler','accepter','acclamer',
        'accolade','accomplir','accorder','accourir','accuser','acerbe','achat','achever',
        'acide','acompte','acquérir','acronyme','acteur','actif','admirer','adopter',
        'adorer','adoucir','adresser','adroit','adulte','aérer','affaire','affecter',
        'afficher','affirmer','agacer','agencer','agile','agiter','agrafer','agréable',
        'agrume','aider','aiguille','aimable','aimer','ajouter','ajuster','alarme',
        'alerte','algèbre','aliment','alléger','allouer','allumer','alourdir','altérer',
        'amasser','ambigu','amener','amical','amour','amuser','analyse','animal',
        'animer','annexer','annoter','aperçu','aplanir','aplomb','apporter','arbitre',
        'ardeur','argent','argument','arrêter','aspect','assez','atteindre','attitude',
        'attrait','audace','augmenter','avancer','avenir','aveugle','avide','avoir',
        'bagage','balance','barrière','bassin','bâtir','batterie','beau','bénéfice',
        'besoin','bêtise','beurre','bienvenu','bizarre','blanchir','bonheur','bouger',
        'braver','briller','brûler','bureau','calme','carbone','carotte','casquette',
        'célèbre','chagrin','chalet','chaleur','chambre','chance','charger','choisir',
        'cible','ciment','circuit','citoyen','citron','clavier','client','cloison',
        'colorier','combler','commun','complet','confier','confort','connaître','conquête',
        'contenu','copier','courage','courant','couvrir','craindre','crédule','creuser',
        'critiquer','croire','cultiver','décrire','défaut','définir','déléguer','départ',
        'dériver','désert','dessiner','détruire','devenir','devoir','différent','difficile',
        'diriger','discuter','domaine','donner','douter','dresser','droit','durable',
        'éclairer','économie','élégant','élever','emboîter','emporter','encadrer','encourager',
        'endurer','engager','enrichir','ensemble','entrée','épargner','équipe','escale',
        'espérer','exister','facteur','famille','farouche','fermer','fêter','fiable',
        'fidèle','figurer','financer','fondre','forger','formuler','fragile','franchir',
        'futur','gagner','garder','général','gérer','glisser','gouverner','grandir',
        'guider','habituer','harmonieux','heureux','honnête','horizon','humain','idéal',
        'imaginer','important','inclure','indice','insérer','isoler','joindre','joueur',
        'juste','lancer','libérer','lier','lire','logique','lumière','maîtriser',
        'marcher','mesurer','modèle','montrer','motiver','naturel','noble','normal',
        'obtenir','offrir','ouvrir','partager','passer','persister','placer','planifier',
        'portée','pratiquer','précis','préserver','produire','proposer','protéger','publier',
        'qualifier','ralentir','rapide','réaliser','réduire','relier','renforcer','répondre',
        'réussir','rêver','risquer','saisir','servir','simple','sonder','soutenir',
        'stable','stocker','suivre','travailler','trier','trouver','unifier','utiliser',
        'valider','vérifier','vivre','vouloir','abcès','abeille','ablation','abricot',
        'abstrait','accès','accroche','acéré','acné','acrobate','actrice','addition',
        'adepte','adjectif','adjoint','admettre','adobe','adverbe','aéroport','affût',
        'agonie','agonir','agrafe','aigle','aiguiser','alcool','algue','alliance',
        'allonger','alphabet','aluminium','ambassade','ambre','amende','amorce','ampleur',
        'ancêtre','ancre','andain','angle','angoisse','anneau','anodin','antenne',
        'anticiper','aperçu','aplati','aplaudir','appel','ardoise','arène','argile',
        'armure','arôme','arpenter','arracher','asile','asphalte','astre','atome',
        'atout','aubaine','aurore','auteur','avaler','avatar','avoine','azote',
        'bague','bailler','balcon','baleine','balle','banlieue','barque','basique',
        'bavard','bazar','béton','bifteck','binôme','bizarre','bloqué','bobine',
        'bocal','bouleau','bourdon','branche','breuvage','brioche','brique','brousse',
        'calcul','camion','canapé','canard','canette','canoë','canule','capable',
        'capote','capsule','captif','caravane','carène','carillon','carpe','cascade',
        'caserne','caverne','cavité','cellule','cendrier','cerise','cerveau','chevron',
        'chiffre','cigale','cigogne','ciment','ciseau','claquer','cligner','clochard',
        'cloporte','cobalt','cocktail','coffre','cohérent','colline','colombe','comète',
        'compas','comptoir','concours','conduit','cône','conflit','congère','conque',
        'consul','contour','convive','coquille','corail','corbeau','corde','corniche',
        'corset','côtelette','coupole','couture','couvée','crabe','crayon','crèche',
        'créneau','cresson','creux','crevette','cristal','croûton','cueillir','culpable',
        'cylindre','dactyle','dalot','dauphin','déboîter','déborder','décaler','décimer',
        'décliner','décorer','défrayer','délier','déloger','dément','dépôt','dérégler',
        'déroger','désigner','déteindre','détour','devancer','dévider','dévorer','diagonale',
        'diamant','dicter','diplôme','discorde','disque','dissoudre','dixième','doctrine',
        'dossier','dragon','drapeau','durcir','ébauche','écaille','écarter','échelle',
        'éclair','éclore','écluse','écolier','écorce','écorner','écouter','écraser',
        'écriture','éduquer','effacer','effiler','effroi','égaler','église','élaguer',
        'emballer','emblème','émettre','émotion','empiler','enclos','endroit','enfance',
        'engrenage','énoncer','enrouler','entier','épingle','équerre','escalier','espion',
        'essence','étable','étage','étaler','étanche','étendre','étoile','étroit',
        'évaluer','évasion','éventail','évoluer','excès','exercer','expédier','exploser',
        'extraire','fabuleux','façade','faïence','fanfare','farceur','fautif','favori',
        'fécond','félin','fenêtre','fervent','feuille','fiction','filière','flamme',
        'flatteur','flèche','fleurir','fleuve','flotteur','fluide','flûte','fondue',
        'fougère','foulard','foyer','fraction','fracture','framboiser','frappant','frayeur',
        'frégate','friable','frivole','froid','fromage','frontière','frugal','fugace',
        'fumée','fusible','gabarit','gâchette','galerie','gardon','garrigue','gazelle',
        'gêner','girafon','girouette','gisement','glacier','glorieux','godiche','gondole',
        'gorille','gouffre','gourde','grabuge','gradin','graffiti','graminée','graphite',
        'gravure','grenat','grève','gribouiller','grimper','grisaille','grognard','grommeler',
        'grotte','guêpe','guéridon','guérir','guetteur','guinguette','guitare','gymnase',
        'gyroscope','hangar','hélice','henné','hercule','hérisson','hirondelle','horloge',
        'houblon','hublot','humus','hydrogène','hygiène','hymne','hypnose','icône',
        'igloo','impasse','imprimer','incendie','incliner','indiquer','indulgent','inerte',
        'infiltrer','infuser','inonder','insister','insulaire','intégrer','inviter','ionique',
        'irrégulier','ivresse','jadis','jaillir','jaloux','jarret','jauger','jeton',
        'jonquille','jungle','kayak','lacune','laiton','lancer','lanterne','lapine',
        'larder','larme','lavabo','légende','légion','lémur','liasse','licorne',
        'lierre','lièvre','limace','limpide','lingot','lisière','litige','loquet',
        'losange','loterie','louche','loutre','lucarne','luette','luire','lune',
        'lustre','luthier','lutin','lynx','macabre','macaron','mâcher','madrier',
        'magenta','magique','maillet','maîtrise','malaxer','manège','mangue','manivelle',
        'maquette','marais','margelle','marleau','marron','masque','méandre','mécène',
        'méfiant','mélodie','menthol','mercure','mérite','métro','meuble','miauler',
        'miette','mimique','minable','minaret','minéral','minime','miroir','missile',
        'mitoyen','mobile','moisson','moitié','molaire','mollusque','momie','monnaie',
        'monture','morale','morceau','morfler','mortier','moteur','mouche','mouette',
        'moufle','mousse','mufle','mulot','muraille','museau','mystère','nacelle',
        'narguer','naseau','nautique','navette','nébuleuse','nénuphar','nervure','nicher',
        'noctambule','nœud','nomade','nonchalant','notaire','nourriture','novice','noyau',
        'nuance','nudiste','nuptial','obscur','obstiner','obtus','occident','offenser',
        'oiseau','ombrage','onctueux','opaque','oracle','orange','orbite','origine',
        'oseille','ossature','outrage','ouverture','ovale','oxygène','pagaie','paillasson',
        'palette','palmier','panache','panier','parure','pâturage','paume','pavillon',
        'pécule','pelage','péniche','perchoir','périmètre','pertinent','pétale','phénomène',
        'pilastre','pirouette','piscine','piston','plainte','plancton','plateau','plongeon',
        'plumage','pochette','pointure','polaire','pollen','polygone','pommier','ponctuel',
        'ponton','pourtour','prétexte','prisonnier','profil','prouesse','pupitre','puzzle',
        'pyramide','quartz','querelle','quinine','racine','radeau','rafale','rainure',
        'ramasser','rampe','rapace','ravin','recoin','rectangle','refuge','régiment',
        'remblai','repère','reptile','résine','résoudre','rétine','rhubarbe','rigole',
        'riposte','riverain','robinet','rognure','roseau','roulement','ruisseau','ruminant',
        'saboteur','safran','saillie','salamandre','salpêtre','sangle','sangsue','sarcasme',
        'sarment','satellite','savane','scarole','sciure','scorpion','sculpture','sécateur',
        'semelle','sénateur','séquoia','serpentin','sillage','silure','siphon','soclage',
        'solive','solvant','sorcier','souflet','soucoupe','soupente','sourdine','soutane',
        'spatule','spirale','squelette','stalactite','strophe','stupeurt','subvenir','sulfure',
        'sureau','surface','suricate','surmener','syllabe','symbole','tablature','tablier',
        'tambour','tamiser','tangente','tapisserie','tartan','tatami','ténacité','terrine',
        'théorie','tilleul','timbre','tison','toboggan','tonnelle','touffe','tourbe',
        'traction','tragique','traîneau','trèfle','treillage','tribunal','tribun','trimestre',
        'tulipe','turbine','tuteur','typique','ulcère','ultimatum','univers','urbain',
        'ustensile','vagabond','vagueur','vaillant','vanille','vapeur','varech','vautour',
        'vecteur','végétal','veinard','velours','vénérer','ventouse','verglas','vermeil',
        'vertige','vétuste','viaduc','vibreur','victoire','vignette','vilain','vinaigre',
        'virevolte','viscère','vitrail','vitrifier','vivace','vocable','volcano','vorace',
        'voûte','voyageur','vrille','xylophone','yacht','yourte','zébrer','zénith',
    ];
}

function generateSeed(int $words = 12): array {
    $list = getBip39Fr();
    $seed = [];
    $max = count($list) - 1;
    for ($i = 0; $i < $words; $i++) {
        $seed[] = $list[random_int(0, $max)];
    }
    return $seed;
}

function seedToHash(array $words): string {
    $phrase = implode(' ', array_map('mb_strtolower', $words));
    return hash('sha256', 'browser_v1_' . $phrase);
}
